# Generated by Django 5.2.7 on 2025-10-30 01:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id_evento', models.AutoField(primary_key=True, serialize=False)),
                ('titulo_evento', models.CharField(max_length=100)),
                ('tipo_evento', models.CharField(choices=[('CUR', 'Curso'), ('TAL', 'Taller'), ('SEM', 'Seminario'), ('CON', 'Conferencia'), ('DIP', 'Diplomado'), ('COG', 'Congreso')], default='CON', max_length=3)),
                ('modalidad_evento', models.CharField(choices=[('PRE', 'Presencial'), ('VIR', 'Virtual'), ('HIB', 'Hibrido')], default='PRE', max_length=3)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('activo', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Plantilla',
            fields=[
                ('id_plantilla', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_plantilla', models.CharField(max_length=100)),
                ('archivo', models.FileField(upload_to='')),
                ('fecha_creacion', models.DateField()),
                ('activa', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Participante',
            fields=[
                ('id_participante', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_participante', models.CharField(max_length=100)),
                ('email_participante', models.EmailField(max_length=254)),
                ('evento_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='constancias.evento')),
            ],
        ),
        migrations.CreateModel(
            name='Constancia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField()),
                ('archivo', models.FileField(upload_to='')),
                ('fecha_creacion', models.DateField()),
                ('id_participante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='constancias.participante')),
            ],
        ),
        migrations.AddField(
            model_name='evento',
            name='plantilla_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='constancias.plantilla'),
        ),
    ]
