# Generated by Django 5.2.7 on 2025-10-31 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constancias', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participante',
            name='evento_id',
        ),
        migrations.AddField(
            model_name='evento',
            name='participantes',
            field=models.ManyToManyField(related_name='eventos', to='constancias.participante'),
        ),
    ]
