# Generated by Django 5.2.7 on 2025-11-22 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constancias', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='descripcion',
            field=models.TextField(blank=True, default='', help_text='Descripción del evento', max_length=150),
        ),
        migrations.AddField(
            model_name='participante',
            name='rol_participante',
            field=models.CharField(default='', help_text='Rol del participante en el evento', max_length=50),
        ),
    ]
