# Generated by Django 5.2.7 on 2025-11-22 01:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constancias', '0002_evento_descripcion_participante_rol_participante'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='duracion_horas',
            field=models.PositiveIntegerField(blank=True, help_text='Duración total del evento en horas académicas', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(500)], verbose_name='Duración (horas)'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='modalidad_evento',
            field=models.CharField(choices=[('PRE', 'Presencial'), ('VIR', 'Virtual'), ('HIB', 'Hibrido')], default='PRE', max_length=3, verbose_name='Modalidad de Evento'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='tipo_evento',
            field=models.CharField(choices=[('CUR', 'Curso'), ('TAL', 'Taller'), ('SEM', 'Seminario'), ('CON', 'Conferencia'), ('DIP', 'Diplomado'), ('COG', 'Congreso')], default='CON', max_length=3, verbose_name='Tipo de Evento'),
        ),
    ]
