# Generated by Django 5.2.7 on 2025-11-01 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constancias', '0002_remove_participante_evento_id_evento_participantes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participante',
            name='email_participante',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
