# Generated by Django 5.2.7 on 2025-11-22 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constancias', '0003_evento_duracion_horas_alter_evento_modalidad_evento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='descripcion',
            field=models.TextField(blank=True, default='', help_text='Descripción del evento', max_length=150, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='participantes',
            field=models.ManyToManyField(blank=True, related_name='eventos', to='constancias.participante'),
        ),
    ]
