# Generated by Django 5.2.7 on 2025-11-12 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constancias', '0003_alter_participante_email_participante'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantilla',
            name='archivo',
            field=models.FileField(upload_to='plantillas/'),
        ),
    ]
