[project]
name = "proyecto-constancias"
version = "0.1.0"
description = "Proyecto generador de constancias"
readme = "README.md"
requires-python = ">=3.10"
dependencies = []

[tool.uv.workspace]
members = [
    "generador_constancias",
]
